// Auto-generated by fetch_newsletters.py — do not edit manually
window.NEWSLETTER_DATA = {
  "generated": "2026-03-26 10:39 UTC",
  "date_range": "25 Mar 2026 – 26 Mar 2026",
  "total_scanned": 19,
  "total_categorised": 11,
  "categories": [
    {
      "key": "hpc_ai",
      "name": "HPC & AI",
      "emoji": "⚡",
      "count": 3,
      "top": [
        {
          "title": "How Anthropic’s Claude Thinks",
          "sender": "ByteByteGo",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/how-anthropics-claude-thinks How AgentField Ships Production Code with 200 Autonomous Agents (Sponsor…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGaG93LWFudGhyb3BpY3MtY2xhdWRlLXRoaW5rcyIsInAiOjE5MTU2MTA3OCwicyI6ODE3MTMyLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3NDQ1MzU5MCwiZXhwIjoyMDkwMDI5NTkwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.Q8_TrsN4spolrgaDBVLa56e5GsAnAHIGlkcYhH8s-dw?",
          "category": "hpc_ai"
        },
        {
          "title": "Inside Siri's reboot  📱,  OpenAI cancels Sora  🎥,  Claude Code auto mode 👨‍💻",
          "sender": "TLDR",
          "date": "25 Mar 2026",
          "snippet": "Apple is testing a standalone app for Siri and an 'Ask Siri' feature. Apple has been working to transform Siri from a traditional voice assistant ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "🪓  OpenAI's Sora gets the axe",
          "sender": "The Rundown AI",
          "date": "25 Mar 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/openai-sora-gets-the-axe?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_GUWR0ZxFuLCb8eocVPm4723yIboaN0ahrDULX88o56tb1Go88zDA3nywoj0rlPsE_HCYYGmt4QW7l3yeRDarqyUvWW6i55VRzsUsNxpX6l85FkswzV3_PakcgDRjVEllhlsmQgplDyeoQrqXRCx7W0jLaIWhoJYZhGmrqmny-JnhgwIk900NmpNDfQhrVDzJyPjukGb4fekaebcr9UyAsCuOoTEJSu_EQVqUr6IrT3jL6E31pcMfxa91fIil7Sr4W7TmNBlnyPxnnO6-uXr7bqwPumDOMdo-WWD3xKY-z161nwqKFtBcj9nO1OlBjr7hap1rRv9KMDSatNnsjUii0-KUSWu8EUNpO6QwBxtjTLP6HqiwWMHd6WP0ClH4dE_Y8B95obMMsCmYNVe_9fAmQ9C6DzWn9Mr3RjGirl9wBe35pRHaiDdF7FfSvN33WAyfJp4IIGVazDYqAyYWp3BD-zj-eKVWm-H6biGmTztRM0Z9s0RgBzhHGKRVironTsD4EWcsGcZiEhk-LbjIqW1VDihTEb0pMRZzTlMZ6__B_BoiBvFmjouMVToyVsOZwgiEfyxpRpRrzYK2A-IA4_GfFanu6TtOk8cHfUBE1B1qvIQWzb3SydxVcRUiO2kb46KRUD0n03pI3RrhgO9OC0pwB6cZU5fC62V2zXmyqlIs3IhD95GjdpcXr2momMMxnROpEgWB1TEj2iL-CX7LLXbZF-3HiGXauth7_65e6-gWYVGgZuDznD-nsU8pg7Hit6EKcW0V4qB48wYBt1V8i0RFIyMXbraveoMdwRA0cgzWVp7Q/4p8/Q0laiAwWQDCMR5h6VUezpA/h0/h001.JjebS6JDry-XbbdVCMkrBtRGu6sZSvFWSo1JhfA66Ew",
          "category": "hpc_ai"
        }
      ],
      "all": [
        {
          "title": "How Anthropic’s Claude Thinks",
          "sender": "ByteByteGo",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/how-anthropics-claude-thinks How AgentField Ships Production Code with 200 Autonomous Agents (Sponsor…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGaG93LWFudGhyb3BpY3MtY2xhdWRlLXRoaW5rcyIsInAiOjE5MTU2MTA3OCwicyI6ODE3MTMyLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3NDQ1MzU5MCwiZXhwIjoyMDkwMDI5NTkwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.Q8_TrsN4spolrgaDBVLa56e5GsAnAHIGlkcYhH8s-dw?",
          "category": "hpc_ai"
        },
        {
          "title": "Inside Siri's reboot  📱,  OpenAI cancels Sora  🎥,  Claude Code auto mode 👨‍💻",
          "sender": "TLDR",
          "date": "25 Mar 2026",
          "snippet": "Apple is testing a standalone app for Siri and an 'Ask Siri' feature. Apple has been working to transform Siri from a traditional voice assistant ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "🪓  OpenAI's Sora gets the axe",
          "sender": "The Rundown AI",
          "date": "25 Mar 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/openai-sora-gets-the-axe?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_GUWR0ZxFuLCb8eocVPm4723yIboaN0ahrDULX88o56tb1Go88zDA3nywoj0rlPsE_HCYYGmt4QW7l3yeRDarqyUvWW6i55VRzsUsNxpX6l85FkswzV3_PakcgDRjVEllhlsmQgplDyeoQrqXRCx7W0jLaIWhoJYZhGmrqmny-JnhgwIk900NmpNDfQhrVDzJyPjukGb4fekaebcr9UyAsCuOoTEJSu_EQVqUr6IrT3jL6E31pcMfxa91fIil7Sr4W7TmNBlnyPxnnO6-uXr7bqwPumDOMdo-WWD3xKY-z161nwqKFtBcj9nO1OlBjr7hap1rRv9KMDSatNnsjUii0-KUSWu8EUNpO6QwBxtjTLP6HqiwWMHd6WP0ClH4dE_Y8B95obMMsCmYNVe_9fAmQ9C6DzWn9Mr3RjGirl9wBe35pRHaiDdF7FfSvN33WAyfJp4IIGVazDYqAyYWp3BD-zj-eKVWm-H6biGmTztRM0Z9s0RgBzhHGKRVironTsD4EWcsGcZiEhk-LbjIqW1VDihTEb0pMRZzTlMZ6__B_BoiBvFmjouMVToyVsOZwgiEfyxpRpRrzYK2A-IA4_GfFanu6TtOk8cHfUBE1B1qvIQWzb3SydxVcRUiO2kb46KRUD0n03pI3RrhgO9OC0pwB6cZU5fC62V2zXmyqlIs3IhD95GjdpcXr2momMMxnROpEgWB1TEj2iL-CX7LLXbZF-3HiGXauth7_65e6-gWYVGgZuDznD-nsU8pg7Hit6EKcW0V4qB48wYBt1V8i0RFIyMXbraveoMdwRA0cgzWVp7Q/4p8/Q0laiAwWQDCMR5h6VUezpA/h0/h001.JjebS6JDry-XbbdVCMkrBtRGu6sZSvFWSo1JhfA66Ew",
          "category": "hpc_ai"
        }
      ]
    },
    {
      "key": "tech",
      "name": "Tech & Gadgets",
      "emoji": "💻",
      "count": 7,
      "top": [
        {
          "title": "Scaling Trino Simply  🌐,  Snowflake Join Trap  🐌,  Death of BI Layers 📉",
          "sender": "TLDR Data",
          "date": "26 Mar 2026",
          "snippet": "Trino Gateway solves the growing complexity of managing dozens of specialized clusters as query volume, concurrency, and workload diversity explode ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "https://ad.doubleclick.net/ddm/trackclk/N2655160.3973022TLDR/B35151171.442761163;dc_trk_aid=636354555;dc_trk_cid=252760689;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;gdpr=${GDPR};gdpr_consent=${GDPR_CONSENT_755};ltd=;dc_tdv=1",
          "category": "tech"
        },
        {
          "title": "Claude Auto Mode  🤖,  ChatGPT product discovery  🛒,  long running harnesses 👨‍💻",
          "sender": "TLDR AI",
          "date": "25 Mar 2026",
          "snippet": "Anthropic released Auto Mode in research preview, enabling Claude to autonomously execute actions with built-in safeguards ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Google Cloud Looker RCE  🔥,  Cars Won't Start After Breach  🚗,  AstraZeneca Data Breach 🧬",
          "sender": "TLDR InfoSec",
          "date": "25 Mar 2026",
          "snippet": "A validation flaw in Google Cloud Looker's directory deletion API allowed attackers to pass `[\"/\"]` as the target path, bypassing `.git` protection ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        }
      ],
      "all": [
        {
          "title": "Scaling Trino Simply  🌐,  Snowflake Join Trap  🐌,  Death of BI Layers 📉",
          "sender": "TLDR Data",
          "date": "26 Mar 2026",
          "snippet": "Trino Gateway solves the growing complexity of managing dozens of specialized clusters as query volume, concurrency, and workload diversity explode ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "https://ad.doubleclick.net/ddm/trackclk/N2655160.3973022TLDR/B35151171.442761163;dc_trk_aid=636354555;dc_trk_cid=252760689;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;gdpr=${GDPR};gdpr_consent=${GDPR_CONSENT_755};ltd=;dc_tdv=1",
          "category": "tech"
        },
        {
          "title": "Claude Auto Mode  🤖,  ChatGPT product discovery  🛒,  long running harnesses 👨‍💻",
          "sender": "TLDR AI",
          "date": "25 Mar 2026",
          "snippet": "Anthropic released Auto Mode in research preview, enabling Claude to autonomously execute actions with built-in safeguards ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Google Cloud Looker RCE  🔥,  Cars Won't Start After Breach  🚗,  AstraZeneca Data Breach 🧬",
          "sender": "TLDR InfoSec",
          "date": "25 Mar 2026",
          "snippet": "A validation flaw in Google Cloud Looker's directory deletion API allowed attackers to pass `[\"/\"]` as the target path, bypassing `.git` protection ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Apple Goes Enterprise  🍎,  All About RSAC 🔐,  AI Needs Better Plumbing 🚰 ",
          "sender": "TLDR IT",
          "date": "25 Mar 2026",
          "snippet": "Apple Business bundles free MDM, email, identity, and app distribution into a single platform for SMBs. This isn’t just a feature release ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Adobe Coworkers  🤖,  Liquid Glass Updates 🧊,  YouTube BrandConnect Rebrand 📺",
          "sender": "TLDR Design",
          "date": "25 Mar 2026",
          "snippet": "Adobe is integrating AI \"coworkers\" into Photoshop, Express, and Acrobat that allow users to make edits using plain text descriptions ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Building a pest control SaaS  🐀,  Markdown for email  📩,  agentic RAG  🔍",
          "sender": "TLDR Dev",
          "date": "25 Mar 2026",
          "snippet": "Email.md converts Markdown into email-safe HTML that renders correctly across all major email clients. Writing email HTML is challenging ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "TypeScript 6.0  🆕,  Architecture Decision Record  📜,  Predicting Indicents ✨",
          "sender": "TLDR DevOps",
          "date": "25 Mar 2026",
          "snippet": "TypeScript 6.0 is a transition release designed to prepare developers for TypeScript 7.0, including alignment changes, new features, and deprecations ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        }
      ]
    },
    {
      "key": "stoic",
      "name": "Stoicism & Philosophy",
      "emoji": "🧘",
      "count": 1,
      "top": [
        {
          "title": "Don't Point Fingers",
          "sender": "StoicWisdoms",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/dont-point-fingers Blame is the most sophisticated form of doing nothing. It masquerades as analysis…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZkb250LXBvaW50LWZpbmdlcnMiLCJwIjoxOTE3NjQxOTYsInMiOjE4MDEzMzMsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc0NDMwODYzLCJleHAiOjIwOTAwMDY4NjMsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.t2ANdZJtONlFv3WP-ee4eb3c1gmH_mQtO8lMHQ2tK1c?",
          "category": "stoic"
        }
      ],
      "all": [
        {
          "title": "Don't Point Fingers",
          "sender": "StoicWisdoms",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/dont-point-fingers Blame is the most sophisticated form of doing nothing. It masquerades as analysis…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZkb250LXBvaW50LWZpbmdlcnMiLCJwIjoxOTE3NjQxOTYsInMiOjE4MDEzMzMsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc0NDMwODYzLCJleHAiOjIwOTAwMDY4NjMsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.t2ANdZJtONlFv3WP-ee4eb3c1gmH_mQtO8lMHQ2tK1c?",
          "category": "stoic"
        }
      ]
    },
    {
      "key": "other",
      "name": "More Reads",
      "emoji": "📌",
      "count": 8,
      "top": [
        {
          "title": "🏆  ARC-AGI-3 resets frontier AI scoreboard",
          "sender": "The Rundown AI",
          "date": "26 Mar 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/arc-agi-3-resets-frontier-ai-scoreboard?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1QiL…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_HohXX-zdpe6o6dAVh7AQBCIIgZUG0l-bvFHMlSCV5O0sYosvUKZWMGNavJuTTF3QgejUHcZxQKS8M2YIRo6SrST792iKhkU-q4zISyxHRjg89279TAocM5jU5xnBiG7ZZPScGua5E2kKzPo3acC4cBlq3XPUpBWoluqe6SusRFQazeUJiSVBJGnJskgkrHArCkU9272MUZXNeeWC7wNPbYtyM4EsPQVUo7YPgLzOgYsIIeGfoBJRShUoM973SDjqBpmoN8fCBHVxJjb09wMWa0fa-TTbnY63sTQDq1qPwVoxnijvl5STfUsXUYBQLZTgPtxFPT_lKuo3jEvrRLh0NcyRHhgvNRiMVmZYfR9e7np0XqsmPaURO6Yr4y3EAQmusmc3WQAq02Dyd0_TV6uN5jrcpEbdIHfJhFAXBGP3jkCtsn9ThzZ8vBpzYy0EE8-glnpvhWJ15UEpWBcRbuF3DxvSjsDxicb2MeqDDPldOlJ3gkR0aYORF2_hZBLGtTcv1z1QXU2h3yOfrnnEb7t-f4D78dxns405u8gWmuZPm163oEWnfBFvZVogsYD-3I2nT_wD4fU9Ul-ixzgk31ZtgntBrlrSFJpsejg46pZ-rh75f_ESokezd0rD2Bw_Q0kGRx2OpYbc23t5I_Sw0MN-RyaAs2PkJIY_DgCjsavmdPiDzV2P4Nr6pfVHL81VbRCrw-Al-64rx-IchfKBWqTEhJ5pMzukvrVYVU3UNEiKXDA4Ah27rn2iOzam69926jS40OdRJoV59sbUqJNp4F2MRbpBaHF3JgNICzr_aEAFRTrZwnjtU3J9qrVmtjtZ-bIY0/4p9/66OWmGNlSGewxKf862HA5w/h0/h001.FLww7W0bVVuEBBPDLzHMPUyw8KWuwIoNZw-qXZTuDok",
          "category": "other"
        },
        {
          "title": "How to hire a marketer who does crazy sh*t ⭐",
          "sender": "Tom's Marketing Ideas",
          "date": "26 Mar 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/how-to-hire-a-marketer-who-does-crazy I have a weird hobby. Since 2020, every time I see a job des…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGaG93LXRvLWhpcmUtYS1tYXJrZXRlci13aG8tZG9lcy1jcmF6eSIsInAiOjE5MTgxMzYwNywicyI6MTgxNTQ3MiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3NzQ1MTkwOTYsImV4cCI6MjA5MDA5NTA5NiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.n8XFlKn_qsn58dJUXVfp0uWurXr99GeXg2dk4NiVveQ?",
          "category": "other"
        },
        {
          "title": "Good Judgment is the New Important Skill for Engineers",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "26 Mar 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/good-judgment-is-the-new-important Intro For a long time, being a great engineer meant havi…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZnb29kLWp1ZGdtZW50LWlzLXRoZS1uZXctaW1wb3J0YW50IiwicCI6MTkyMTY3NTk4LCJzIjoxMTE1ODE1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3NDQ5ODEyMywiZXhwIjoyMDkwMDc0MTIzLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.CJZg3J8bzug8eSRole0FeI1245fz88vbnZk8z194L6U?",
          "category": "other"
        }
      ],
      "all": [
        {
          "title": "🏆  ARC-AGI-3 resets frontier AI scoreboard",
          "sender": "The Rundown AI",
          "date": "26 Mar 2026",
          "snippet": "^**[Read Online](https://www.therundown.ai/p/arc-agi-3-resets-frontier-ai-scoreboard?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOiJKV1QiL…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.dSnm3kaGd0BkNqLYPjeMf75St_4h4uVDlb2B1USeB_HohXX-zdpe6o6dAVh7AQBCIIgZUG0l-bvFHMlSCV5O0sYosvUKZWMGNavJuTTF3QgejUHcZxQKS8M2YIRo6SrST792iKhkU-q4zISyxHRjg89279TAocM5jU5xnBiG7ZZPScGua5E2kKzPo3acC4cBlq3XPUpBWoluqe6SusRFQazeUJiSVBJGnJskgkrHArCkU9272MUZXNeeWC7wNPbYtyM4EsPQVUo7YPgLzOgYsIIeGfoBJRShUoM973SDjqBpmoN8fCBHVxJjb09wMWa0fa-TTbnY63sTQDq1qPwVoxnijvl5STfUsXUYBQLZTgPtxFPT_lKuo3jEvrRLh0NcyRHhgvNRiMVmZYfR9e7np0XqsmPaURO6Yr4y3EAQmusmc3WQAq02Dyd0_TV6uN5jrcpEbdIHfJhFAXBGP3jkCtsn9ThzZ8vBpzYy0EE8-glnpvhWJ15UEpWBcRbuF3DxvSjsDxicb2MeqDDPldOlJ3gkR0aYORF2_hZBLGtTcv1z1QXU2h3yOfrnnEb7t-f4D78dxns405u8gWmuZPm163oEWnfBFvZVogsYD-3I2nT_wD4fU9Ul-ixzgk31ZtgntBrlrSFJpsejg46pZ-rh75f_ESokezd0rD2Bw_Q0kGRx2OpYbc23t5I_Sw0MN-RyaAs2PkJIY_DgCjsavmdPiDzV2P4Nr6pfVHL81VbRCrw-Al-64rx-IchfKBWqTEhJ5pMzukvrVYVU3UNEiKXDA4Ah27rn2iOzam69926jS40OdRJoV59sbUqJNp4F2MRbpBaHF3JgNICzr_aEAFRTrZwnjtU3J9qrVmtjtZ-bIY0/4p9/66OWmGNlSGewxKf862HA5w/h0/h001.FLww7W0bVVuEBBPDLzHMPUyw8KWuwIoNZw-qXZTuDok",
          "category": "other"
        },
        {
          "title": "How to hire a marketer who does crazy sh*t ⭐",
          "sender": "Tom's Marketing Ideas",
          "date": "26 Mar 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/how-to-hire-a-marketer-who-does-crazy I have a weird hobby. Since 2020, every time I see a job des…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGaG93LXRvLWhpcmUtYS1tYXJrZXRlci13aG8tZG9lcy1jcmF6eSIsInAiOjE5MTgxMzYwNywicyI6MTgxNTQ3MiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3NzQ1MTkwOTYsImV4cCI6MjA5MDA5NTA5NiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.n8XFlKn_qsn58dJUXVfp0uWurXr99GeXg2dk4NiVveQ?",
          "category": "other"
        },
        {
          "title": "Good Judgment is the New Important Skill for Engineers",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "26 Mar 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/good-judgment-is-the-new-important Intro For a long time, being a great engineer meant havi…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZnb29kLWp1ZGdtZW50LWlzLXRoZS1uZXctaW1wb3J0YW50IiwicCI6MTkyMTY3NTk4LCJzIjoxMTE1ODE1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3NDQ5ODEyMywiZXhwIjoyMDkwMDc0MTIzLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.CJZg3J8bzug8eSRole0FeI1245fz88vbnZk8z194L6U?",
          "category": "other"
        },
        {
          "title": "[AINews] The Biggest Claude Launch of All Time",
          "sender": "AINews",
          "date": "26 Mar 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-the-biggest-claude-launch It is considered uncouth in the news business to reflect on things that…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLXRoZS1iaWdnZXN0LWNsYXVkZS1sYXVuY2giLCJwIjoxOTIxNjg4MzEsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc0NDk3MzY3LCJleHAiOjIwOTAwNzMzNjcsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.KBXpf3UdsGnEwUoyxYPLW8U1xSiG4de5hF2NDwAYn6o?",
          "category": "other"
        },
        {
          "title": "The 53 Concepts for Highly Effective Mobile System Design",
          "sender": "Neo Kim",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/mobile-system-design Get my system design playbook for FREE on newsletter signup: Share this …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRm1vYmlsZS1zeXN0ZW0tZGVzaWduIiwicCI6MTkxNjczMTIxLCJzIjoxNTExODQ1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3NDQ1NDQ3MCwiZXhwIjoyMDkwMDMwNDcwLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.qVdrdvZKrMBQB0lJxuIAnalHR62eKMQVdHrtfUgNcoQ?",
          "category": "other"
        },
        {
          "title": "Nobody Knows",
          "sender": "Kent Beck — Still Burning Podcast",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://tidyfirst.substack.com/p/nobody-knows Kent Beck kicks off Still Burning with a fireside manifest for geeks navigating a wor…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly90aWR5Zmlyc3Quc3Vic3RhY2suY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnRpZHlmaXJzdC5zdWJzdGFjay5jb20lMkZwJTJGbm9ib2R5LWtub3dzIiwicCI6MTkyMDA5NTYyLCJzIjoyNTY4MzgsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzc0NDQxMDQ3LCJleHAiOjIwOTAwMTcwNDcsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.QEZeU6CGbDpSlyauLfnM8HM-kYiECFNmQpuqO2g1z6o?",
          "category": "other"
        },
        {
          "title": "The Telephone Game of Software",
          "sender": "🌀 Refactoring",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://refactoring.fm/p/the-telephone-game-of-software My favorite byproduct of the AI shift in engineering is that it is making u…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9yZWZhY3RvcmluZy5mbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZyZWZhY3RvcmluZy5mbSUyRnAlMkZ0aGUtdGVsZXBob25lLWdhbWUtb2Ytc29mdHdhcmUiLCJwIjoxOTE3NjEwNjAsInMiOjY0MDk5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc3NDQyODM5NSwiZXhwIjoyMDkwMDA0Mzk1LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.unGXb2_4iBdU6t73mNt7Br0wT8r_hUhcPlyPUNT8h40?",
          "category": "other"
        },
        {
          "title": "[AINews] Apple's War on Slop",
          "sender": "AINews",
          "date": "25 Mar 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-apples-war-on-slop There were few bright spots today, as Microsoft AI execuhired AI2 leadership […",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWFwcGxlcy13YXItb24tc2xvcCIsInAiOjE5MjA2NTE3MywicyI6MTA4NDA4OSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3NzQ0MTk2ODUsImV4cCI6MjA4OTk5NTY4NSwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.b3OamCIZviYPEwuQ2phpSKfOpWnmH4R67e3RXqSWNYc?",
          "category": "other"
        }
      ]
    }
  ]
};
