// Auto-generated by fetch_newsletters.py — do not edit manually
window.NEWSLETTER_DATA = {
  "generated": "2026-08-21 08:28 UTC",
  "date_range": "20 Aug 2026 – 21 Aug 2026",
  "total_scanned": 25,
  "total_categorised": 10,
  "categories": [
    {
      "key": "hpc_ai",
      "name": "HPC & AI",
      "emoji": "⚡",
      "count": 2,
      "top": [
        {
          "title": "[AINews] Poolside gets $12B reverse-execuhire to NVIDIA; founders stay for $1B, employees go for $6B, Infraco scal…",
          "sender": "AINews",
          "date": "21 Aug 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-poolside-gets-12b-reverse Less than a month ago we had just featured Poolside’s Model Factory wit…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLXBvb2xzaWRlLWdldHMtMTJiLXJldmVyc2UiLCJwIjoyMTIxMDQ1MzMsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3MjkxMjQzLCJleHAiOjIxMDI4NjcyNDMsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.I2qCqW9cdpIu6LRwBjnIwZKtu0Ay-I9VE_zz3z6WJgM?",
          "category": "hpc_ai"
        },
        {
          "title": "Lovable’s  TanStack migration 🔧,  OpenAI slows model dev 🚦,  Postgres for everything 🏆",
          "sender": "TLDR Dev",
          "date": "20 Aug 2026",
          "snippet": "The migration of lovable.dev from Next.js to the TanStack Start framework improved performance and provided better alignment with their hosting ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        }
      ],
      "all": [
        {
          "title": "[AINews] Poolside gets $12B reverse-execuhire to NVIDIA; founders stay for $1B, employees go for $6B, Infraco scal…",
          "sender": "AINews",
          "date": "21 Aug 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-poolside-gets-12b-reverse Less than a month ago we had just featured Poolside’s Model Factory wit…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLXBvb2xzaWRlLWdldHMtMTJiLXJldmVyc2UiLCJwIjoyMTIxMDQ1MzMsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3MjkxMjQzLCJleHAiOjIxMDI4NjcyNDMsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.I2qCqW9cdpIu6LRwBjnIwZKtu0Ay-I9VE_zz3z6WJgM?",
          "category": "hpc_ai"
        },
        {
          "title": "Lovable’s  TanStack migration 🔧,  OpenAI slows model dev 🚦,  Postgres for everything 🏆",
          "sender": "TLDR Dev",
          "date": "20 Aug 2026",
          "snippet": "The migration of lovable.dev from Next.js to the TanStack Start framework improved performance and provided better alignment with their hosting ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "hpc_ai"
        }
      ]
    },
    {
      "key": "product",
      "name": "Product Management",
      "emoji": "🗺️",
      "count": 1,
      "top": [
        {
          "title": "To Invent Waymo, They Had to Reinvent PM",
          "sender": "Lenny's Newsletter",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/cp/212081371 Unsubscribe https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xld…",
          "link": "https://substack.com/redirect/aa1985d2-755c-4220-97e2-1efc31bda827?j=eyJ1IjoiN2Nsa25iIn0.O-PU_p3YxNsPpIcNo2SnqduSPxlu3BMzlf29XX0Kpxs",
          "category": "product"
        }
      ],
      "all": [
        {
          "title": "To Invent Waymo, They Had to Reinvent PM",
          "sender": "Lenny's Newsletter",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/cp/212081371 Unsubscribe https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xld…",
          "link": "https://substack.com/redirect/aa1985d2-755c-4220-97e2-1efc31bda827?j=eyJ1IjoiN2Nsa25iIn0.O-PU_p3YxNsPpIcNo2SnqduSPxlu3BMzlf29XX0Kpxs",
          "category": "product"
        }
      ]
    },
    {
      "key": "tech",
      "name": "Tech & Gadgets",
      "emoji": "💻",
      "count": 7,
      "top": [
        {
          "title": "AWS Gives You $1,000. Or $300,000. Same Form",
          "sender": "The VC Corner",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/aws-gives-you-1000-or-300000-same Two founders fill out the same AWS application on the same afternoo…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGYXdzLWdpdmVzLXlvdS0xMDAwLW9yLTMwMDAwMC1zYW1lIiwicCI6MjEyMDE2ODIwLCJzIjoyMTI1MTgzLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzI2MjgwMiwiZXhwIjoyMTAyODM4ODAyLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.9f7VihTG_i3IRMHTioWzYlmPoPZgDMJM3F4TxV2kSFw?",
          "category": "tech"
        },
        {
          "title": "Muse Video leaks  📹,  Ramp Router launch 🔀,  why Stripe bought OpenRouter 💰",
          "sender": "TLDR AI",
          "date": "20 Aug 2026",
          "snippet": "Meta's Muse Video model is now in closed beta. The model has native audio, and early outputs show strong detail and temporal consistency ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Breaking Secure Boot ⛓️‍💥,  Prompt Injection  Worm🪱,  CareCloud Breach Grows to 3.7M  🏥",
          "sender": "TLDR InfoSec",
          "date": "20 Aug 2026",
          "snippet": "A signature check alone doesn't prove a device is safe. This post breaks secure boot into four failure buckets: did the check run ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        }
      ],
      "all": [
        {
          "title": "AWS Gives You $1,000. Or $300,000. Same Form",
          "sender": "The VC Corner",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.thevccorner.com/p/aws-gives-you-1000-or-300000-same Two founders fill out the same AWS application on the same afternoo…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhldmNjb3JuZXIuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy50aGV2Y2Nvcm5lci5jb20lMkZwJTJGYXdzLWdpdmVzLXlvdS0xMDAwLW9yLTMwMDAwMC1zYW1lIiwicCI6MjEyMDE2ODIwLCJzIjoyMTI1MTgzLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzI2MjgwMiwiZXhwIjoyMTAyODM4ODAyLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.9f7VihTG_i3IRMHTioWzYlmPoPZgDMJM3F4TxV2kSFw?",
          "category": "tech"
        },
        {
          "title": "Muse Video leaks  📹,  Ramp Router launch 🔀,  why Stripe bought OpenRouter 💰",
          "sender": "TLDR AI",
          "date": "20 Aug 2026",
          "snippet": "Meta's Muse Video model is now in closed beta. The model has native audio, and early outputs show strong detail and temporal consistency ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Breaking Secure Boot ⛓️‍💥,  Prompt Injection  Worm🪱,  CareCloud Breach Grows to 3.7M  🏥",
          "sender": "TLDR InfoSec",
          "date": "20 Aug 2026",
          "snippet": "A signature check alone doesn't prove a device is safe. This post breaks secure boot into four failure buckets: did the check run ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "SSD Prices Explode  💾,  AI Is Adding to IT Workloads  🤖,  Wi-Fi 7 Takes Off 📶",
          "sender": "TLDR IT",
          "date": "20 Aug 2026",
          "snippet": "Enterprise SSD prices rose another 5% in July and remain about 6.5 times higher than in Q3 2025. VDURA prices a 30TB TLC drive at $22,600 ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Apple Maps Ads  📍,  Spotify Running Mode 🏃,  Apple AI Calendar  📅",
          "sender": "TLDR Design",
          "date": "20 Aug 2026",
          "snippet": "Apple launched \"Ads on Maps\" on Friday, letting US and Canadian businesses buy ad placements with no minimum spend, photo uploads ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "YouTube vs Netflix  🎬,  Stripe declares Singularity  🤖,  half-day vulnerabilities 👨‍💻 ",
          "sender": "TLDR",
          "date": "20 Aug 2026",
          "snippet": "YouTube is offering millions of dollars to popular channels for exclusivity. The company has yet to finalize any deals with creators ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Inside DuckDB 2.0  🦆,  ACID for AI Agents ✅,  Variant Lands in Iceberg  🪆",
          "sender": "TLDR Data",
          "date": "20 Aug 2026",
          "snippet": "DuckDB’s upcoming 2.0 release turns the database into a much broader platform, adding client/server operation, triggers, first-class semi-structured ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        }
      ]
    },
    {
      "key": "other",
      "name": "More Reads",
      "emoji": "📌",
      "count": 15,
      "top": [
        {
          "title": "Burnout is a System Issue 🪫 — with Dominika Rogala",
          "sender": "🌀 Refactoring",
          "date": "21 Aug 2026",
          "snippet": "View this post on the web at https://refactoring.fm/p/burnout-is-a-system-issue-with-dominika Listen now: YouTube [ https://substack.com/redirect/c5540db2-410a-…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9yZWZhY3RvcmluZy5mbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZyZWZhY3RvcmluZy5mbSUyRnAlMkZidXJub3V0LWlzLWEtc3lzdGVtLWlzc3VlLXdpdGgtZG9taW5pa2EiLCJwIjoyMTE5NjkzNzcsInMiOjY0MDk5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzMwMDQ2MSwiZXhwIjoyMTAyODc2NDYxLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.20Z2mUaDT_2QLFCFVD63U5kFzwqAUly3gd23KdQ04mA?",
          "category": "other"
        },
        {
          "title": "The right way to make wrong decisions",
          "sender": "Nord Media",
          "date": "21 Aug 2026",
          "snippet": "************************************* The right way to make wrong decisions ************************************* You are excellent at auditing business and an …",
          "link": "https://735d96f7.click.convertkit-mail4.com/e5u7gqvne7u7hldn8x7f8h87x4w7du5go069k2x92krq3v4o64rpzvrgm8098vrgxl75lo7vonxerzxvqo8ndqmglze7rzgm4878rvor9m7opo2ozeq8zmrvo9mf0lw33/z2hgh7uel4mvpnhzu0/aHR0cHM6Ly9ub3JkbWVkaWEuY29tL2Nhc2Utc3R1ZGllcw==",
          "category": "other"
        },
        {
          "title": "AI’s Bar Mitzvah Moment? From Hope & Hype to Hard Business Questions!",
          "sender": "Aswath Damodaran from Musings on Markets",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://aswathdamodaran.substack.com/p/ais-bar-mitzvah-moment-from-hope In a world where AI enters almost every conversation, it ta…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9hc3dhdGhkYW1vZGFyYW4uc3Vic3RhY2suY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmFzd2F0aGRhbW9kYXJhbi5zdWJzdGFjay5jb20lMkZwJTJGYWlzLWJhci1taXR6dmFoLW1vbWVudC1mcm9tLWhvcGUiLCJwIjoyMTIwNjc0NTMsInMiOjgxNTY2NywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODcyNjE2NTcsImV4cCI6MjEwMjgzNzY1NywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.qwo9369RLazrtCsIfSQ4KZovfZDzOz6ZfxOnFpHVTuw?",
          "category": "other"
        }
      ],
      "all": [
        {
          "title": "Burnout is a System Issue 🪫 — with Dominika Rogala",
          "sender": "🌀 Refactoring",
          "date": "21 Aug 2026",
          "snippet": "View this post on the web at https://refactoring.fm/p/burnout-is-a-system-issue-with-dominika Listen now: YouTube [ https://substack.com/redirect/c5540db2-410a-…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9yZWZhY3RvcmluZy5mbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZyZWZhY3RvcmluZy5mbSUyRnAlMkZidXJub3V0LWlzLWEtc3lzdGVtLWlzc3VlLXdpdGgtZG9taW5pa2EiLCJwIjoyMTE5NjkzNzcsInMiOjY0MDk5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzMwMDQ2MSwiZXhwIjoyMTAyODc2NDYxLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.20Z2mUaDT_2QLFCFVD63U5kFzwqAUly3gd23KdQ04mA?",
          "category": "other"
        },
        {
          "title": "The right way to make wrong decisions",
          "sender": "Nord Media",
          "date": "21 Aug 2026",
          "snippet": "************************************* The right way to make wrong decisions ************************************* You are excellent at auditing business and an …",
          "link": "https://735d96f7.click.convertkit-mail4.com/e5u7gqvne7u7hldn8x7f8h87x4w7du5go069k2x92krq3v4o64rpzvrgm8098vrgxl75lo7vonxerzxvqo8ndqmglze7rzgm4878rvor9m7opo2ozeq8zmrvo9mf0lw33/z2hgh7uel4mvpnhzu0/aHR0cHM6Ly9ub3JkbWVkaWEuY29tL2Nhc2Utc3R1ZGllcw==",
          "category": "other"
        },
        {
          "title": "AI’s Bar Mitzvah Moment? From Hope & Hype to Hard Business Questions!",
          "sender": "Aswath Damodaran from Musings on Markets",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://aswathdamodaran.substack.com/p/ais-bar-mitzvah-moment-from-hope In a world where AI enters almost every conversation, it ta…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9hc3dhdGhkYW1vZGFyYW4uc3Vic3RhY2suY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmFzd2F0aGRhbW9kYXJhbi5zdWJzdGFjay5jb20lMkZwJTJGYWlzLWJhci1taXR6dmFoLW1vbWVudC1mcm9tLWhvcGUiLCJwIjoyMTIwNjc0NTMsInMiOjgxNTY2NywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODcyNjE2NTcsImV4cCI6MjEwMjgzNzY1NywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.qwo9369RLazrtCsIfSQ4KZovfZDzOz6ZfxOnFpHVTuw?",
          "category": "other"
        },
        {
          "title": "The /wayfinder Skill: Navigating the “Fog of War” of Planning",
          "sender": "Latent.Space",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/wayfinder-skill We’re currently developing a new series about skills, with the aim of giving you a regul…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGd2F5ZmluZGVyLXNraWxsIiwicCI6MjExNjk1ODI1LCJzIjoxMDg0MDg5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzI1OTY1NCwiZXhwIjoyMTAyODM1NjU0LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.ouHS7Lgq6eLtluArTuMmw-Xmy6F9gEJKY0auL4L_mro?",
          "category": "other"
        },
        {
          "title": "How to Build AI Agents That Don’t Start Over When They Fail",
          "sender": "Neo Kim",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/durable-ai-agents Get my system design playbook for FREE on newsletter signup: Share this let…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRmR1cmFibGUtYWktYWdlbnRzIiwicCI6MjExNjk0MjUzLCJzIjoxNTExODQ1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzI0Njg5NCwiZXhwIjoyMTAyODIyODk0LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.rVr8SP88AJvcERw2ki9Oiv_gptIAP3JW_35GWkoPJwE?",
          "category": "other"
        },
        {
          "title": "Schema Evolution: Changing the Contract Without Breaking What Runs",
          "sender": "ByteByteGo",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/schema-evolution-changing-the-contract A schema change is usually one of the most difficult types of …",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGc2NoZW1hLWV2b2x1dGlvbi1jaGFuZ2luZy10aGUtY29udHJhY3QiLCJwIjoyMTE3NTEwMzcsInMiOjgxNzEzMiwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODcyNDA5MDMsImV4cCI6MjEwMjgxNjkwMywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.Ri-OmX21oluo4ot4X521zYOiuhZmuRnV6Fmxo8YfkqU?",
          "category": "other"
        },
        {
          "title": "How Shutterstock Builds AI-Native Engineering Teams",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/how-shutterstock-builds-ai-native This newsletter is sponsored by Sonar [ https://substack.…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZob3ctc2h1dHRlcnN0b2NrLWJ1aWxkcy1haS1uYXRpdmUiLCJwIjoyMTE1NTI3NzQsInMiOjExMTU4MTUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3MjM4Nzc2LCJleHAiOjIxMDI4MTQ3NzYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.D0zkM11KUWDaa5CFxgtsX8kKWMdmdZbpcmbBCdKyu_g?",
          "category": "other"
        },
        {
          "title": "How to 8x Your Code Output Using Context Engineering",
          "sender": "The AI Corner",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.the-ai-corner.com/p/context-engineering-claude-code-playbook Anthropic’s Engineers 8x Their Output In June 2026 Anthrop…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhlLWFpLWNvcm5lci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnRoZS1haS1jb3JuZXIuY29tJTJGcCUyRmNvbnRleHQtZW5naW5lZXJpbmctY2xhdWRlLWNvZGUtcGxheWJvb2siLCJwIjoyMTA3Mzg4MTMsInMiOjY4NTA1NDQsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3MjM3MzM0LCJleHAiOjIxMDI4MTMzMzQsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.zqjzku54EJtX7uoJYOXIxS-6DDcvrwIqlUYZUfpLGpo?",
          "category": "other"
        },
        {
          "title": "🤖  Unitree founder gains $13B overnight",
          "sender": "The Rundown Robotics",
          "date": "20 Aug 2026",
          "snippet": "^**[Read Online](https://robotnews.therundown.ai/p/unitree-founder-gains-13b-overnight?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJzY3JpYmVyX2lkIjoiZT…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.GQOM8q4ys-vZgCzT2HGlhRR7J-xBT4QBkF5vOL2NbkA9HgM60G060N3ZNmi3VRw7b1irnNpDpTqRzE85mILWGShFJBncde-RvlQuM_JNRfsiXWxqtP1wmlyGxb2-sBdlPwCY649rz-Swp6FlxbtMJfgGn03UQ3zxTQDyZ_6w3eiO_RwP3IFYR31HUUcqfERAJZP88mPaAFJwR2I5ssyCk2g-Yu-tEj3wiMGzxW2jbmtDXolSEMzqxLQBfKQoglMM6zT8aHf1BU-RxqeE8E3rXUYD7IKEf-yO3IxLGzgG3hIJuGY8OoDIhTMe2ypy8kAxJorROtxZjB5_DXK6Pe6VyrSm8oKfil2VUFPz0eqdXqZbp07MqYqhafS68e9cvolQm5lC946n5RRZIYnEZOrxnuqCagYwY-FJfi0HEjsYgx-OTeNbw4eGL9dndBxAKO_bHaKGwZvmiOnEfL9-eRgTi-VrjtEFp69AD9LCf26OQ44seUrZw2ZqCzEpnb4TIu9QUiXoeEK7UKrXzexEi4J0r-dOvjdVu_VY4PmFQKrGwiu-h3Fc8ZcOeXFn6bbQLwvjAcq9x89nYHF3SuGbuCbU9srUPV8pJA8QfFSQQ_c4lxk-NyGo2rCDHywp-HKyApwuk8OOfdWg5NX6V_frxYZt44iTewb6IwDscsIilWtyT0cvOwpgdaKuBJvUqgu_YAdbfLvGAkpvYMGjovn50zcpYLIWyhGUmUYhxQX9gbYqzhA/4tc/kTGMSYIoSwuV8EVKdW1XCw/h0/h001.k1jw4IoOxz2aeM5VOC9GIVRsnul1aJhTfdpaBLCYzno",
          "category": "other"
        },
        {
          "title": "Cheaper Tokens, Higher Bills and AI-Designed Viruses",
          "sender": "AIwire Weekly Update",
          "date": "20 Aug 2026",
          "snippet": "To view this email in your browser, click here https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3kft%2BMDhoA7RLDtVG…",
          "link": "https://tabor.omeclk.com/portal/public/ViewCommInBrowser.jsp?Sv4%2BeOSSucxf98VAw5ob5oLnoWy6vQy3kft%2BMDhoA7RLDtVGm940948n7wTEbycVRfOjOd9lw%2FkrIzn1Mhe1GA%3D%3DA",
          "category": "other"
        },
        {
          "title": "👀  Stripe becomes first non AI lab to say it",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "20 Aug 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/4fcf0966-89da-4b5e-b20a-373199ea1…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGU5UHfxXWYxUS1qCFaLZ7Ay-re3mxsn04DTHRtx6QDgR1oc-rmRTDRIdhnMNk9z1va9mN2lc4PlnxhLFz9MX-9qT6Uy6yhye7LmQTqiWAtMXsayO056CjeMber0etaAsHBXSYKbbwZlbKlhuNc0wTbQFVl91jVgCzWrznXNEl5f6rVsYfrUwwDmqidV2i-2KramKGllKTT5I7ePx_qfqDpkvSMdVAfwsA0omdkyaQRHWiIAFzd5SgZXbW_y9wHYuDAjdnNO7XG7yMuof7UUGPaeitwFBLuifLLgLwtQbAhzHVNcRqKm70ez1BIWnr_hrEBEi_s4E-CZUEHZ-VAGZHJcCG44Bwdo7ZfiGeUiPJVUvjPe3-Whi_YNIhziYesM02E2zxHBDpTWZ7VS0bY2N44ZyL4Rm2ECma2Bhe2b6UIChSzRzr2sMtLzsgK6otQM5rsmaACt_YsYf1eEGfJnsaTLV9dSN0sdh6bSf4fixYmfhJg1sxe_K5leuyEP18yRRzwQykfRseeQqYF2usci-UYIun0KfTxGJDHNn02FBT1xLwshLUQGRV2Cgkhh2bcqcjvwdiY6l865z7ZYmmkYAXRoXW1gJ9pdtpPONTEBcC7rIXb5VMMO7KhInKmKN_009iI2xZws5iS3awFafCzIkRKkvsud5otvf3V6trv1rbDkGf6govt2IYu52sWfCss7cfY4s081tc3ANjfLhWnhIphFFFXTnnSxJLueP189OQDif3dKGbIPgOAr6AJd7KiIKQg/4tc/OQxxZuRkRBKWxjVCaj5QsA/h0/h001.2gF12sGHFn0Exu7NP_Ntyink8w9uMynTcpzqczpR79k",
          "category": "other"
        },
        {
          "title": "👀  Your coding agents can DM you in Slack",
          "sender": "The Code",
          "date": "20 Aug 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/09e01702-21fd-4e87-b991-9fd71b832…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.kro7WBsAmEsY5mGgiUDePbOdMF_BvViPt7FxYKgxL9vNxs20acgMgBcc145tGXv56noj8psfoNjJ93vEsTYzy8YoMVs9lkLgx3VTYAD5PP3P2C5IBRETqh-JrbkFLLdcjH_nYdnUg9Imn6BPu0JX1qLLdgeGLOtplA9UlLh9bNhN0i0Q3Zkw1csTeEJQl1qlF9s8ep1tFP_RI8uQHdeX5R6jm_RcJVCdl_pR0v4Fw0yi96u16xiPZO6soz_iEnhu12AruUnQl1BYaiyWM0XCejMQhyl9etGHfOovctdUCCDxz7SgeE1_Z1XGt8tsz8YfXZtX6z1NSgpW42KE5y-paM4ncXtyFVzIXssGR7eKlPY453s19cvPlcGHWjwM6cnm_u5BBObSYU7TJDXpns65sAXy7630LVwuE2_5Jkw97RJ_6jf27OMI08dDVcNEwTgzzXP2Gz0mcy69I57kzhTkKhgkozH6oLpKJIV9HJHd8tgjgBPUZsrFCNcnl51Yjcq5onF4bGyJ9Bc7mNTi3YdaXhlHvjOWIzzN7jf_Nj0W6WHGu7OgSwbOtA3alt3flpChqwr-LyBbYVgRB3E7M2Ww5HGOx_nVeq-rNtAdp9ZdqCCMsfucadcZxnPKFdrBGGJcXJGP_0M8IiGyGPDCLJlBuett0j210GGyecd8DFZ8nAxNzYJRBcq5rin_P1DUNi7UUc05Ru4jEYAHHKwJ0hGvf2Os6SIfCu-b6-J6YrhKDz2wtqVyawlMkie2BkIWIQKh2s5_o8sxwE6ue77gnCr6DQ/4tc/VSyFnfzfQyatZyXE3aw-xw/h0/h001.f1zBsR7J7Rnj_kcVOXypUlPmFifQx4EwSP5JBU2Wt-c",
          "category": "other"
        },
        {
          "title": "🧬  Claude adds protein design to its resume",
          "sender": "The Rundown AI",
          "date": "20 Aug 2026",
          "snippet": "^**[Read Online](https://therundownai.beehiiv.com/p/claude-adds-protein-design-to-its-resume?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiO…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.KT4rQsO6sHS_v2VASG2xupywTByilB7vBf1gbeXMnd8_JiJ3T_F3NCunxkbuGUIY77Bsv5qR50SZ9RyQD8u4d6iFLbEsLwhPuUCoUTXixnRrYhqfBb3unFXMe1-MJPSu-SQHsoI3bUWIKoCklNe65CMpDdP7b_jz4-7hD5oCPtWdvhks4qskK5qX8ntz0UzceiLdJzT5Ov7H0yAuCwB4LvQh1ZgdM01L3B8Y-NJTSxccAC4PIPQjOxIIXpRGi4MYYk0-fpxCPxN0YtobhU7TbjOH4dCSx628fdyDmdoVqq0EAOD7iSdf7p-rB0SnJCT_KSCcBsnzFehUM0hJArIiWu91FsQiVoMiMwW4t3M0IdEb_aNVqMuNB8wdhLH0BnyKoKAESUuJXYogpRh1MSjKEQ5UXOulV7DSoeKyKh9qhffMSL4MR-lj95ZcXkQUwLEVXDIA_3dMQ98B6dnWBgn24TAvZhzraAmjAB-qqkLw4OJShOhHvUBxlryLRPZK_YZaBEhXtx2ojU1JqBKjxgEILywnQXabf-pPPBVTqzr7IUriC1A2aJaD1f3FyY2pejHYutG64z2QmTlDntIH_xvscoXtR8yDMQqV7SpK-7S3OAmEpvZoh2AVIxMHj_JezfjIdaYEQBgGm53qzAjtmrrCReRUvCdhUCg0IPtqklAMrx4dw1xBXnLUFEh2w9_ngRJVsu612NqnCO4tDzdnUGDSx37iIxQ-ENCfKuWv3zS6XigAmtZNeSOxezsw1mk0fuwAqqByZZuJmsmfaoKBUnTw-p6DFXt2FRc9QAkGmN7c-YI/4tc/9pUlTGp-RRqKw7uOo7bUkw/h0/h001.x0U25z4p79MXx0-6_Vlf6n-xAaeL8bL4_AovrpHk_O0",
          "category": "other"
        },
        {
          "title": "The \"secret ingredient\" of the world's best ads 🧪",
          "sender": "Tom's Marketing Ideas",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/the-secret-ingredient-of-the-worlds Today’s post is written by a guest: SHLOMO GENCHIN [ https://s…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGdGhlLXNlY3JldC1pbmdyZWRpZW50LW9mLXRoZS13b3JsZHMiLCJwIjoyMDkyNzk2MDEsInMiOjE4MTU0NzIsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3MjA2MDkxLCJleHAiOjIxMDI3ODIwOTEsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.dzZuMuWX8j9fEDyN9fqAN0tUnA7kwZ7PX8giFdLX2IQ?",
          "category": "other"
        },
        {
          "title": "[AINews] Death of Params: Z.ai CEO Jie Tang on GLM 5.3 and the new\r\n Post-training Scaling Law",
          "sender": "AINews",
          "date": "20 Aug 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-death-of-params-zai-ceo-jie We’ve covered GLM 5.2 [ https://substack.com/redirect/895ca24a-5023-4…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWRlYXRoLW9mLXBhcmFtcy16YWktY2VvLWppZSIsInAiOjIxMTk1MjcyNCwicyI6MTA4NDA4OSwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODcyMDMxOTcsImV4cCI6MjEwMjc3OTE5NywiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.v6OnmSuw-nZ_OAEN06NQcxrx_LCtnsHQJoNbaJklKiU?",
          "category": "other"
        }
      ]
    }
  ]
};
