// Auto-generated by fetch_newsletters.py — do not edit manually
window.NEWSLETTER_DATA = {
  "generated": "2026-08-25 08:31 UTC",
  "date_range": "24 Aug 2026 – 25 Aug 2026",
  "total_scanned": 25,
  "total_categorised": 13,
  "categories": [
    {
      "key": "hpc_ai",
      "name": "HPC & AI",
      "emoji": "⚡",
      "count": 5,
      "top": [
        {
          "title": "HPC AI // Sync Issue 29",
          "sender": "HPCwire Sync",
          "date": "24 Aug 2026",
          "snippet": "#outlook a { padding: 0; } .body{ font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Geneva, Verdana, sans-serif; width: 100% !important; -webk…",
          "link": "https://tabor.dragonforms.com/tabor_pref&amp;r=5801D9452678H4Z",
          "category": "hpc_ai"
        },
        {
          "title": "Anthropic Expands Defender Access to Mythos 🛡️,  Leaked AWS Keys 🔑,  Auditing AI Coding Agent Actions 🤖",
          "sender": "TLDR InfoSec",
          "date": "24 Aug 2026",
          "snippet": "Researchers have trained LoRA to embed a dormant backdoor into Qwen 3.5 2B that will activate on a later date, executing a shell command ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "📈  Nvidia says AI-flation isn't slowing down",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "24 Aug 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/d614632e-a0d9-482e-a2d6-95d4e7869…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGVvD48REoUs-xfZhc1sqOa9aDO10GwhRox7slswmc1ToWIvKf7DKIoa_g4ve4xY9d6iO5fRAk1RYzH03K9-7NSKk-E-AnmxfHkajMOLv9w7gOb7qIiR8ZLvCfDQ-P5lGg79Xn7E89PvmPWAd2CjVTlCKp44m1Nxr7tU6sr-rNajwtFalUw4dGa3FoYGQdvp6Ihlj38xnofXKDCEVuWurw9XZT9ZWR-1_j_i-r3rZEwHhsnW5HGvo5kchh2uf_bDUajXbPYRIXTS1S0FXi70BgWLUDXK1FsfentSwpaVHBD0n_bAH82UnO4jqJ70nNhdwGCcfiyq97IhOes0Vm_Xig3FS5RdXZmoZ8_NGu4c9W9noYa34yesp-Gjuklii3HfjWeKaQG7OHdikbmwrwdFV0-NegP7YGuyBMHmWZFLyNUZ9I4LEvrJCE3WgjXEcXbjFW27uq9g-m8hqYHHYU_w5lBaWlTvXj7wC6zToaWUGAdmLF1Gp-UgMpOyvjETWgyp0RvJhE-Z5tqZIzCfrwCPgHbjajxIyI1uwHlNIe55BjRojuhrRl1MUcDeRC4kqU5U0HCsDkGYJ7EOew4BTJD487xKKRA9qc2KOSJ8eWf0Yd5H-nL9lksdMYaCVwBGEUWD5_X_pwQZAWX--Se5ja0pPZS2lPmWvdqYs3JfpBqa3ujbQPhvjz9yKRVm9Es0PWRJ9xQDgsLdFZubh0u_PS0IMkyi_YC4EmBrWzvradwACPuYkw/4tg/xcEwKWbxQ76a2ZxRk_8BMA/h0/h001.UvWQ9aNZk_AbEyrh0olLvGk-pNT5RKdtuzs3bkO9WmA",
          "category": "hpc_ai"
        }
      ],
      "all": [
        {
          "title": "HPC AI // Sync Issue 29",
          "sender": "HPCwire Sync",
          "date": "24 Aug 2026",
          "snippet": "#outlook a { padding: 0; } .body{ font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Geneva, Verdana, sans-serif; width: 100% !important; -webk…",
          "link": "https://tabor.dragonforms.com/tabor_pref&amp;r=5801D9452678H4Z",
          "category": "hpc_ai"
        },
        {
          "title": "Anthropic Expands Defender Access to Mythos 🛡️,  Leaked AWS Keys 🔑,  Auditing AI Coding Agent Actions 🤖",
          "sender": "TLDR InfoSec",
          "date": "24 Aug 2026",
          "snippet": "Researchers have trained LoRA to embed a dormant backdoor into Qwen 3.5 2B that will activate on a later date, executing a shell command ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "📈  Nvidia says AI-flation isn't slowing down",
          "sender": "Superhuman  –  Zain Kahn",
          "date": "24 Aug 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/d614632e-a0d9-482e-a2d6-95d4e7869…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.QR8PDET7GVRZS9oWC_jpgH-qigySh3hAoVuoVNaPnGVvD48REoUs-xfZhc1sqOa9aDO10GwhRox7slswmc1ToWIvKf7DKIoa_g4ve4xY9d6iO5fRAk1RYzH03K9-7NSKk-E-AnmxfHkajMOLv9w7gOb7qIiR8ZLvCfDQ-P5lGg79Xn7E89PvmPWAd2CjVTlCKp44m1Nxr7tU6sr-rNajwtFalUw4dGa3FoYGQdvp6Ihlj38xnofXKDCEVuWurw9XZT9ZWR-1_j_i-r3rZEwHhsnW5HGvo5kchh2uf_bDUajXbPYRIXTS1S0FXi70BgWLUDXK1FsfentSwpaVHBD0n_bAH82UnO4jqJ70nNhdwGCcfiyq97IhOes0Vm_Xig3FS5RdXZmoZ8_NGu4c9W9noYa34yesp-Gjuklii3HfjWeKaQG7OHdikbmwrwdFV0-NegP7YGuyBMHmWZFLyNUZ9I4LEvrJCE3WgjXEcXbjFW27uq9g-m8hqYHHYU_w5lBaWlTvXj7wC6zToaWUGAdmLF1Gp-UgMpOyvjETWgyp0RvJhE-Z5tqZIzCfrwCPgHbjajxIyI1uwHlNIe55BjRojuhrRl1MUcDeRC4kqU5U0HCsDkGYJ7EOew4BTJD487xKKRA9qc2KOSJ8eWf0Yd5H-nL9lksdMYaCVwBGEUWD5_X_pwQZAWX--Se5ja0pPZS2lPmWvdqYs3JfpBqa3ujbQPhvjz9yKRVm9Es0PWRJ9xQDgsLdFZubh0u_PS0IMkyi_YC4EmBrWzvradwACPuYkw/4tg/xcEwKWbxQ76a2ZxRk_8BMA/h0/h001.UvWQ9aNZk_AbEyrh0olLvGk-pNT5RKdtuzs3bkO9WmA",
          "category": "hpc_ai"
        },
        {
          "title": "Alibaba’s  $10B AI bet 💰,  Altman on OpenAI 🎙️,  AI hits the power grid ⚡",
          "sender": "TLDR IT",
          "date": "24 Aug 2026",
          "snippet": "Alibaba plans to raise roughly $10 billion to expand its AI infrastructure, chips, data centers, and model development. The raise comes days ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "hpc_ai"
        },
        {
          "title": "Apple foldables  📱,  Nvidia price hikes 📈,  future of MCP 👨‍💻 ",
          "sender": "TLDR",
          "date": "24 Aug 2026",
          "snippet": "Apple is set to introduce its foldable iPhone at a launch event on or around September 9. Samsung has stolen some of the thunder from the launch ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "hpc_ai"
        }
      ]
    },
    {
      "key": "product",
      "name": "Product Management",
      "emoji": "🗺️",
      "count": 2,
      "top": [
        {
          "title": "🎙️ How I AI: Grok Bot + Grok 4.6—what’s great (and what’s still hype) & Lessons from spending $20,000 on Devin in…",
          "sender": "Lenny's Newsletter",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/p/how-i-ai-grok-bot-grok-46whats-great Grok Bot + Grok 4.6—what’s great (and what’s still hype) Li…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xldHRlci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3Lmxlbm55c25ld3NsZXR0ZXIuY29tJTJGcCUyRmhvdy1pLWFpLWdyb2stYm90LWdyb2stNDZ3aGF0cy1ncmVhdCIsInAiOjIxMTc3NjY5OSwicyI6MTA4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3NTg0NTM2LCJleHAiOjIxMDMxNjA1MzYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.p74W8u4hdhPscy-rj0fd8epbRdgE2e1WjSc94xiURZU?",
          "category": "product"
        },
        {
          "title": "No more slow software  ⚡️,  finding problems to solve  🧑‍🔧,  new MCP roadmap  🌱",
          "sender": "TLDR Dev",
          "date": "24 Aug 2026",
          "snippet": "The cost of software optimization has drastically decreased, enabling more developers to implement performance improvements that previously ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "product"
        }
      ],
      "all": [
        {
          "title": "🎙️ How I AI: Grok Bot + Grok 4.6—what’s great (and what’s still hype) & Lessons from spending $20,000 on Devin in…",
          "sender": "Lenny's Newsletter",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://www.lennysnewsletter.com/p/how-i-ai-grok-bot-grok-46whats-great Grok Bot + Grok 4.6—what’s great (and what’s still hype) Li…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGVubnlzbmV3c2xldHRlci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3Lmxlbm55c25ld3NsZXR0ZXIuY29tJTJGcCUyRmhvdy1pLWFpLWdyb2stYm90LWdyb2stNDZ3aGF0cy1ncmVhdCIsInAiOjIxMTc3NjY5OSwicyI6MTA4NDUsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3NTg0NTM2LCJleHAiOjIxMDMxNjA1MzYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.p74W8u4hdhPscy-rj0fd8epbRdgE2e1WjSc94xiURZU?",
          "category": "product"
        },
        {
          "title": "No more slow software  ⚡️,  finding problems to solve  🧑‍🔧,  new MCP roadmap  🌱",
          "sender": "TLDR Dev",
          "date": "24 Aug 2026",
          "snippet": "The cost of software optimization has drastically decreased, enabling more developers to implement performance improvements that previously ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "product"
        }
      ]
    },
    {
      "key": "tech",
      "name": "Tech & Gadgets",
      "emoji": "💻",
      "count": 5,
      "top": [
        {
          "title": "DeepSeek Flash Vision  👀,  Claude Mythos security  🛡️,  inside Grok Bot 🤖",
          "sender": "TLDR AI",
          "date": "24 Aug 2026",
          "snippet": "DeepSeek V4-Flash-Vision-Exp is an experimental multimodal model that adds image understanding to its text capabilities. It nearly matches Opus 4.8 ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "CXMT's DRAM built on stolen IP  ⚖️, SpaceX recovers Starship  🌊,  Robot Games shifts to work tests  🤖",
          "sender": "TLDR Hardware",
          "date": "24 Aug 2026",
          "snippet": "Testimony in a South Korean criminal case alleges that CXMT, now China's largest DRAM maker, was founded with no in-house research capability ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Apple Layoffs  🍎,  ChatGPT Photo Shortcut 📸,  Slack Vibe Coding 🧑‍💻",
          "sender": "TLDR Design",
          "date": "24 Aug 2026",
          "snippet": "Apple has laid off more than 200 employees across its Vision Pro, Siri, and software engineering teams as part of a broader restructuring effort ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        }
      ],
      "all": [
        {
          "title": "DeepSeek Flash Vision  👀,  Claude Mythos security  🛡️,  inside Grok Bot 🤖",
          "sender": "TLDR AI",
          "date": "24 Aug 2026",
          "snippet": "DeepSeek V4-Flash-Vision-Exp is an experimental multimodal model that adds image understanding to its text capabilities. It nearly matches Opus 4.8 ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "CXMT's DRAM built on stolen IP  ⚖️, SpaceX recovers Starship  🌊,  Robot Games shifts to work tests  🤖",
          "sender": "TLDR Hardware",
          "date": "24 Aug 2026",
          "snippet": "Testimony in a South Korean criminal case alleges that CXMT, now China's largest DRAM maker, was founded with no in-house research capability ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "Apple Layoffs  🍎,  ChatGPT Photo Shortcut 📸,  Slack Vibe Coding 🧑‍💻",
          "sender": "TLDR Design",
          "date": "24 Aug 2026",
          "snippet": "Apple has laid off more than 200 employees across its Vision Pro, Siri, and software engineering teams as part of a broader restructuring effort ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌…",
          "link": "",
          "category": "tech"
        },
        {
          "title": "AI Reliability Incidents  🔥,  DigitalOcean Inference Router  🚦,  Azure Regional Outage ‼️",
          "sender": "TLDR DevOps",
          "date": "24 Aug 2026",
          "snippet": "AI agents acting as autonomous first responders may successfully resolve many routine incidents, but their ability to take operational actions also ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        },
        {
          "title": "The Politics Behind Metrics  🏛️, Unlearning Pandemic Demand  🦠,  The Art of Indexing ⚡",
          "sender": "TLDR Data",
          "date": "24 Aug 2026",
          "snippet": "Dashboards are not neutral: the metrics and visuals they prioritize shape what leaders see, fund, and act on, while harder-to-measure realities ‌ ‌ ‌ ‌ ‌ ‌ ‌ ‌ …",
          "link": "",
          "category": "tech"
        }
      ]
    },
    {
      "key": "stoic",
      "name": "Stoicism & Philosophy",
      "emoji": "🧘",
      "count": 1,
      "top": [
        {
          "title": "Don’t Let Opinions Control You",
          "sender": "StoicWisdoms",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/dont-let-opinions-control-you An opinion is an event in someone else’s mind. It is produced by a his…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZkb250LWxldC1vcGluaW9ucy1jb250cm9sLXlvdSIsInAiOjIxMjM5NzcwMSwicyI6MTgwMTMzMywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODc1NjM1NTIsImV4cCI6MjEwMzEzOTU1MiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.-dllF_yeQwdORY8IBd5EP4zUpQvZMap7RfDwAR3zX7w?",
          "category": "stoic"
        }
      ],
      "all": [
        {
          "title": "Don’t Let Opinions Control You",
          "sender": "StoicWisdoms",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://www.stoicwisdoms.com/p/dont-let-opinions-control-you An opinion is an event in someone else’s mind. It is produced by a his…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cuc3RvaWN3aXNkb21zLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZ3d3cuc3RvaWN3aXNkb21zLmNvbSUyRnAlMkZkb250LWxldC1vcGluaW9ucy1jb250cm9sLXlvdSIsInAiOjIxMjM5NzcwMSwicyI6MTgwMTMzMywiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODc1NjM1NTIsImV4cCI6MjEwMzEzOTU1MiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.-dllF_yeQwdORY8IBd5EP4zUpQvZMap7RfDwAR3zX7w?",
          "category": "stoic"
        }
      ]
    },
    {
      "key": "other",
      "name": "More Reads",
      "emoji": "📌",
      "count": 12,
      "top": [
        {
          "title": "[AINews] Andrew Ng gets into AI Engineering",
          "sender": "AINews",
          "date": "25 Aug 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-andrew-ng-gets-into-ai-engineering We’ve lost count of how many adoption milestones have been pas…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWFuZHJldy1uZy1nZXRzLWludG8tYWktZW5naW5lZXJpbmciLCJwIjoyMTI2Mzg0NjIsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3NjI2NDI2LCJleHAiOjIxMDMyMDI0MjYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.9urFhLR6ymnHtQ158h3e7zOXzlOGmrsaEF70CSvg2Eo?",
          "category": "other"
        },
        {
          "title": "Integrating AI into Storytelling",
          "sender": "Scott Galloway",
          "date": "25 Aug 2026",
          "snippet": "View this post on the web at https://www.profgmedia.com/p/integrating-ai-into-storytelling The dawg days of August — see what I did there? — are upon us. I’m ba…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cucHJvZmdtZWRpYS5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnByb2ZnbWVkaWEuY29tJTJGcCUyRmludGVncmF0aW5nLWFpLWludG8tc3Rvcnl0ZWxsaW5nIiwicCI6MjEyNjI5NDUxLCJzIjo3MTU3NDExLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzYxNjg4OCwiZXhwIjoyMTAzMTkyODg4LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.KEC-gHUoDQehAtLByjVKO8VZsEC33Dp06i3y4Q-bYdI?",
          "category": "other"
        },
        {
          "title": "Your ESP now lives inside Claude. Yes really.",
          "sender": "Nord Media",
          "date": "24 Aug 2026",
          "snippet": "********************************************* Your ESP now lives inside Claude. Yes really. ********************************************* Export-CSV-Squint. Tha…",
          "link": "https://735d96f7.click.convertkit-mail4.com/qdu2dwe372a7h4logrnflh8nrk92da9v5g0zm73z7mxrdwn50nxp8wxv6kgzkwxv34q945qw523ex83wr5k2lr6v48eqx8v6nkqkxw5xz6q5p5758erk86xw5z6tkgzrr/qvh8h8udk2m3e2sguk/aHR0cHM6Ly95b3VyLm9tbmlzZW5kLmNvbS9rb2R5bm9yZHF1aXN0",
          "category": "other"
        }
      ],
      "all": [
        {
          "title": "[AINews] Andrew Ng gets into AI Engineering",
          "sender": "AINews",
          "date": "25 Aug 2026",
          "snippet": "View this post on the web at https://www.latent.space/p/ainews-andrew-ng-gets-into-ai-engineering We’ve lost count of how many adoption milestones have been pas…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubGF0ZW50LnNwYWNlL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5sYXRlbnQuc3BhY2UlMkZwJTJGYWluZXdzLWFuZHJldy1uZy1nZXRzLWludG8tYWktZW5naW5lZXJpbmciLCJwIjoyMTI2Mzg0NjIsInMiOjEwODQwODksImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3NjI2NDI2LCJleHAiOjIxMDMyMDI0MjYsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.9urFhLR6ymnHtQ158h3e7zOXzlOGmrsaEF70CSvg2Eo?",
          "category": "other"
        },
        {
          "title": "Integrating AI into Storytelling",
          "sender": "Scott Galloway",
          "date": "25 Aug 2026",
          "snippet": "View this post on the web at https://www.profgmedia.com/p/integrating-ai-into-storytelling The dawg days of August — see what I did there? — are upon us. I’m ba…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cucHJvZmdtZWRpYS5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnByb2ZnbWVkaWEuY29tJTJGcCUyRmludGVncmF0aW5nLWFpLWludG8tc3Rvcnl0ZWxsaW5nIiwicCI6MjEyNjI5NDUxLCJzIjo3MTU3NDExLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzYxNjg4OCwiZXhwIjoyMTAzMTkyODg4LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.KEC-gHUoDQehAtLByjVKO8VZsEC33Dp06i3y4Q-bYdI?",
          "category": "other"
        },
        {
          "title": "Your ESP now lives inside Claude. Yes really.",
          "sender": "Nord Media",
          "date": "24 Aug 2026",
          "snippet": "********************************************* Your ESP now lives inside Claude. Yes really. ********************************************* Export-CSV-Squint. Tha…",
          "link": "https://735d96f7.click.convertkit-mail4.com/qdu2dwe372a7h4logrnflh8nrk92da9v5g0zm73z7mxrdwn50nxp8wxv6kgzkwxv34q945qw523ex83wr5k2lr6v48eqx8v6nkqkxw5xz6q5p5758erk86xw5z6tkgzrr/qvh8h8udk2m3e2sguk/aHR0cHM6Ly95b3VyLm9tbmlzZW5kLmNvbS9rb2R5bm9yZHF1aXN0",
          "category": "other"
        },
        {
          "title": "Fine Tuning: A Deep Dive",
          "sender": "Neo Kim",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://newsletter.systemdesign.one/p/llm-fine-tuning-guide-with-lora-and-qlora Get my system design playbook for FREE on newslette…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLnN5c3RlbWRlc2lnbi5vbmUvc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGbmV3c2xldHRlci5zeXN0ZW1kZXNpZ24ub25lJTJGcCUyRmxsbS1maW5lLXR1bmluZy1ndWlkZS13aXRoLWxvcmEtYW5kLXFsb3JhIiwicCI6MjA5MjU4Njg5LCJzIjoxNTExODQ1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzU4ODc0NiwiZXhwIjoyMTAzMTY0NzQ2LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.0qniwnRg2RMSMfOIXgFyojnZ3yrXe-t628elcRbKl7M?",
          "category": "other"
        },
        {
          "title": "Why Code Verification Matters More Than Ever in the Age of AI",
          "sender": "ByteByteGo",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://blog.bytebytego.com/p/why-code-verification-matters-more How to give an agent a task instead of a token (Sponsored) [ https…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9ibG9nLmJ5dGVieXRlZ28uY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRmJsb2cuYnl0ZWJ5dGVnby5jb20lMkZwJTJGd2h5LWNvZGUtdmVyaWZpY2F0aW9uLW1hdHRlcnMtbW9yZSIsInAiOjIxMjE3NjQzOCwicyI6ODE3MTMyLCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzU4NjM2MSwiZXhwIjoyMTAzMTYyMzYxLCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.1ouZ7O8DY8ghq_2n0HjyqbuEeVxUm4hG5eFjE70DX3c?",
          "category": "other"
        },
        {
          "title": "Sam Altman: Intelligence Got 100x Cheaper in 2 Years. His Next Bet Is $5\r\n Trillion",
          "sender": "The AI Corner",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://www.the-ai-corner.com/p/sam-altman-ai-price-drop Intelligence has a price, and the price falls on a schedule. “The price fo…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cudGhlLWFpLWNvcm5lci5jb20vc3Vic2NyaWJlP3V0bV9zb3VyY2U9ZW1haWwmdXRtX2NhbXBhaWduPWVtYWlsLXN1YnNjcmliZSZyPTdjbGtuYiZuZXh0PWh0dHBzJTNBJTJGJTJGd3d3LnRoZS1haS1jb3JuZXIuY29tJTJGcCUyRnNhbS1hbHRtYW4tYWktcHJpY2UtZHJvcCIsInAiOjIxMDg1MjQyMSwicyI6Njg1MDU0NCwiZiI6dHJ1ZSwidSI6NDQ0NDI1MTU5LCJpYXQiOjE3ODc1ODI0NDYsImV4cCI6MjEwMzE1ODQ0NiwiaXNzIjoicHViLTAiLCJzdWIiOiJsaW5rLXJlZGlyZWN0In0.6A3cqH8F5Ov8mjUZaFohee9W_JFIZnIOJZktf1RxaCA?",
          "category": "other"
        },
        {
          "title": "⚡️ Humanoids beat Usain Bolt’s  100m record",
          "sender": "The Rundown Robotics",
          "date": "24 Aug 2026",
          "snippet": "^**[Read Online](https://robotnews.therundown.ai/p/humanoids-beat-usain-bolt-100m-record?jwt_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWJzY3JpYmVyX2lkIjoi…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.GQOM8q4ys-vZgCzT2HGlhRR7J-xBT4QBkF5vOL2NbkDwiEzHqPjnwUkTDuqivmG_CMHLkv05_OTOdswKG62Bg7XTFxgsSvkg_IUZmagKQiROleeSrdNsVX0wVw-yTmPlYXIA7XIzmJftR33x9xBA1rQXoAFF7MOjRcGLoi8PQv2B1nOEXnG8bSr3g864JXhHhgygN0DNyBaCAjEj6By1J_ZljacS7rLLNCqCnj9o6aIBNE2LyjOuCpFfXmohsZdB3FS3VpsmrcJi3gwVQtQTR0nWD-2fN4Z2QNUbtn8uiHeZw5ZvpVsg-RVXEvZrexol7oECOYuFBA3tsDvwHMEAS93x05lVac_RkwH2kr67CS84Z47vAC0PSFDxw8SK2qnhhECfyUZr8y1EYggqJt-m28FZdeRSiBdUbgV3cdOuitlC64yqkS5NbMluHlfkMXe5GB7CaEIlvvW7rbDjT8WBdZv5o55EpBKhUlF7B6Pvhk2GxsqbvVBikajeKGK1dLZaMsnz-iKpTzg_Ir3a8UaGsse0lrh4CvFMdDZ46HVmbYOvqEeZ0Y1YGU1-wgqYM5YnnNJoIRONNNYCQYQLBjY0YFs9WN4QawYR1p5Ppwd3fkB54Aqd8gkM2MNsSgLl-lWN4FZZGjRyvi-CMnLhy14n2JObFnqPmTJtFO-ciqjBRq5HrmPl6Bdv3ESgcaMWqvb4odrd7q2rakua6PkRvXwPfVmWNQAhpz_Sqm9g-CkPgJk/4tg/nMT6ucXPSe-nWUu-4Idoaw/h0/h001.Rrxzq3CzGjqaQH4vUXlChvO6ShQAZdOum-wj1GooDT4",
          "category": "other"
        },
        {
          "title": "Good Culture is the Biggest Productivity Hack, Not AI",
          "sender": "Gregor Ojstersek from Engineering Leadership",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://newsletter.eng-leadership.com/p/good-culture-is-the-biggest-productivity This newsletter is sponsored by Unblocked [ https:…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9uZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZuZXdzbGV0dGVyLmVuZy1sZWFkZXJzaGlwLmNvbSUyRnAlMkZnb29kLWN1bHR1cmUtaXMtdGhlLWJpZ2dlc3QtcHJvZHVjdGl2aXR5IiwicCI6MjEyMzIzNDU0LCJzIjoxMTE1ODE1LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzU4MDgxNiwiZXhwIjoyMTAzMTU2ODE2LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.1trdmvlsMNoR-90l4pQaL6H2nrNwsVco82tD4IhCue0?",
          "category": "other"
        },
        {
          "title": "🔥  Building future websites for agents",
          "sender": "The Code",
          "date": "24 Aug 2026",
          "snippet": "View image: (https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/307273bf-0742-49c9-9997-ccd2fe79e…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.kro7WBsAmEsY5mGgiUDePbOdMF_BvViPt7FxYKgxL9uQ-i43qDxjGoX7MIafHXHUKBd4HKGYzcyhExJMQgtY9xMQAeVPWvMvfZU9ZqnvWEvrYK6ZVEaqrkldkqYu6GhV2dy4EBvlWO0hheiH8u4j_zqSqD4a1Ex0v35u8-Sgt1U4wtMDkW3AtjIrXW1dgn_kEvUIAphffviKRKtfskh_JNLImpeaESarFEvQjJ2Wb0qj_EOyCyKx9cCm_Dg7nKIxK0W5PT_8N_KYsf8PBUEyzAZ2pXXubspEXe3z3tClMaFi3YSya5zpzvD1SivOPS5UywPGV1hp0BEARprHnpW6SflW6VVIc1910bJUe_1aA4E-pQsT-2T_IvvD5RrfhO5EVHVZAqM3sOcPFNGqfZx7u91eUl8NWNOQB1paqma94tcp2i2mCwEaYnPT2eI307VdKAVV69gryx2Vq-UoBPVAU4KCJ0goAtDDeUEBrhTTpRkIRQ1CwsQlYq2is_Ng3fsEl5nIgbeBMEAEODCo9ZUcWL7UI3Wd5RGnXdmDqVb5Jq1lNqMtfeEVuju4tvJ64j78n6noADS4X5yldKpAAFFpRGxMg9-U0zA908E0NRHVPzGYU40Umo7uvymd9Z67RCp6sPfZd9T-i78smRHUaXEL1x7YTg71Wtze0l5djDDUIV-qQJqJSfRaSPcgh6cLQ1h06p44Z8N35LVlisGCx-qGSmYlyrgZZVrnB5Zx4WCdXWm90c1dth0q_sm97SlZsYn7XNvmfBS02hrJnjQKCxp0cJ8pQj2HucrH1Su__LfkIMY36996xUURMFeACA2o3XKV/4tg/thvIMQ1SR1ywukyIJ5csvQ/h0/h001.5WiIo3PSfcbr5YdNTlj2UMxdvyaWfDIuwW8NwcfefAQ",
          "category": "other"
        },
        {
          "title": "🕵️  A mystery challenger at the AI frontier",
          "sender": "The Rundown AI",
          "date": "24 Aug 2026",
          "snippet": "^**[Read Online](https://therundownai.beehiiv.com/p/a-mystery-challenger-at-the-ai-frontier?_bhlid=4eaa234680798ad3bdb45514b5705f029891f88c&jwt_token=eyJ0eXAiOi…",
          "link": "https://link.mail.beehiiv.com/ss/c/u001.KT4rQsO6sHS_v2VASG2xupywTByilB7vBf1gbeXMnd-AdEbyvXKfAOm_QItrwRmUFyAYSWuqWvF8f-SZaQkHgC2P_MViammtcw6Nm5PmLacOL2U1mYjmzYorIM6GfW7SfCcRCeTz3fDY5PWDvfngJpYWOzYK2cLZ3j3u6BBjOtq9deV5OZJcZYOQQaLD1B5l86kXlyu56RM38h3PvyRPdy_uH15on3U2gs-KIveFr2fz-6wPyTxxvUJ4WmvhLsiIFRuHLt68UmFTfznou4MThIqjrtSFaD2VDJrybeXoYOTErssl0IcvSjO_GRjF933KHAY2AXLh8-ymKEzqSr13au0z8SphmiZGND6GaYApEtZgrB9gH5IL0wHWGIlAW7KwwuJIJiNagmIYEPcrv1oQaythb3JnFgwGlqs1j9cT-1-gMFykhSrgB1YI_d_Ruer7RrjOQUXbfl5T4uvOW5JlhU_FV4W2hfOLX70mOQ6q0DFCv7TGvPxmgPw6HQhI09npAZ_KriLuXiP30ZlSbUt3G4lZI_Tnap2LM7nyB3aoIDBqA_HMJPzQhRpbDdBqyUIs43wswAfzpf2ik5zCaGRdP2BsEbESsnTMDxfHsUVgH5Er7A6Zmq8170vkKvTE8CaU7grfBoouplEuPM9UkBJet37Fg-0YWuYPekob9TvSJwfcNWdSDw2MVpYblHjVJxgexLPr_09duzk2wWdJOCpmCQkCimXbrAi6lybSK9pERAnKpgaTTdndp-w4FDM_Lc0SDKqok7x77UL2x5s-ebOG-L4IrsUhVdUMfdQEqyzjl1c/4tg/ocokw-X8RwCyvykr_LMY1w/h0/h001.5gR7APNMPfTY9tQjLYu7PqOT5frL6WaxHwjULVjCRhA",
          "category": "other"
        },
        {
          "title": "LinkedIn lets you choose your post's URL 🌐",
          "sender": "Tom's Marketing Ideas",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://www.marketingideas.com/p/linkedin-lets-you-choose-your-posts Hey, Tom [ https://substack.com/redirect/63f14c05-a6df-49ab-b7…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly93d3cubWFya2V0aW5naWRlYXMuY29tL3N1YnNjcmliZT91dG1fc291cmNlPWVtYWlsJnV0bV9jYW1wYWlnbj1lbWFpbC1zdWJzY3JpYmUmcj03Y2xrbmImbmV4dD1odHRwcyUzQSUyRiUyRnd3dy5tYXJrZXRpbmdpZGVhcy5jb20lMkZwJTJGbGlua2VkaW4tbGV0cy15b3UtY2hvb3NlLXlvdXItcG9zdHMiLCJwIjoyMTIxNjQwNDAsInMiOjE4MTU0NzIsImYiOnRydWUsInUiOjQ0NDQyNTE1OSwiaWF0IjoxNzg3NTYwNDk0LCJleHAiOjIxMDMxMzY0OTQsImlzcyI6InB1Yi0wIiwic3ViIjoibGluay1yZWRpcmVjdCJ9.AXvcVy8rLDIQZTrih-i9limdC_wRQDPaemX1PIkxyEg?",
          "category": "other"
        },
        {
          "title": "Protecting reasoning, getting your hands dirty, and weekly readings 📚",
          "sender": "🌀 Refactoring",
          "date": "24 Aug 2026",
          "snippet": "View this post on the web at https://refactoring.fm/p/protecting-reasoning-getting-your Hey, Luca [ https://substack.com/redirect/176e0af6-f84a-4896-96c6-f69e9a…",
          "link": "https://substack.com/redirect/2/eyJlIjoiaHR0cHM6Ly9yZWZhY3RvcmluZy5mbS9zdWJzY3JpYmU_dXRtX3NvdXJjZT1lbWFpbCZ1dG1fY2FtcGFpZ249ZW1haWwtc3Vic2NyaWJlJnI9N2Nsa25iJm5leHQ9aHR0cHMlM0ElMkYlMkZyZWZhY3RvcmluZy5mbSUyRnAlMkZwcm90ZWN0aW5nLXJlYXNvbmluZy1nZXR0aW5nLXlvdXIiLCJwIjoyMTIxMTkyMTcsInMiOjY0MDk5LCJmIjp0cnVlLCJ1Ijo0NDQ0MjUxNTksImlhdCI6MTc4NzU1ODAzOSwiZXhwIjoyMTAzMTM0MDM5LCJpc3MiOiJwdWItMCIsInN1YiI6ImxpbmstcmVkaXJlY3QifQ.Y0Bdg02GoxFTfnM3LHNN7yO8RGS1P7qT-Z5VQ0wjAPo?",
          "category": "other"
        }
      ]
    }
  ]
};
